using System.Text;
using FMC125.Utils;

namespace FMC125.Rfid;

/// <summary>
/// Decodes the <see cref="IoElement.Value"/> bytes of IO ID 109 ("Serial Packet").
///
/// Background — FMC125 RS-232 Delimiter mode:
///   When the FMC125 is configured in RS-232 Delimiter mode (firmware ≥ 03.28.05)
///   and a packet arrives from the external device (e.g. an RFID reader), the device
///   packages it as a <em>Serial Packet</em> IO element with ID 109.
///
///   This IO element is placed in the variable-length (NX) group of the Codec 8E
///   AVL record, and its Value bytes carry a 2-byte envelope before the actual data:
///
///     Byte 0        — Index (sequence counter, starts at 0, increments per packet)
///     Byte 1        — DataLength (byte count of the following Payload)
///     Bytes 2..N+1  — Payload (raw RS-232 bytes between the configured delimiters;
///                     max 255 bytes; RFID reader output arrives here)
///
///   The record is generated with HIGH priority and EventIO ID = 109.
///   IO 109 is ONLY present in Delimiter mode; all other RS-232 modes (RFID HID,
///   RFID MF7, TCP, etc.) do NOT produce this IO element.
///
/// Decoding the Payload field:
///   Depending on the connected reader / firmware, the RS-232 payload may contain:
///     • A plain EPC/TID hex string encoded as ASCII.
///     • A framed reader response (prefix bytes + EPC/TID + suffix + RSSI, etc.)
///
///   This decoder attempts multiple strategies in order:
///     1. Pure printable-ASCII that looks like a hex string — return as-is.
///     2. Known framed patterns — strip the frame, extract the tag field.
///     3. Heuristic tail extraction — find the longest run that looks like EPC/TID.
///     4. Fallback — return the full payload hex.
/// </summary>
public static class RfidDecoder
{
  /// <summary>
  /// IO ID for the Serial Packet element generated by RS-232 Delimiter mode.
  /// This element is placed in the variable-length (NX) group of a Codec 8E record.
  /// It is ONLY present when RS-232 is in Delimiter mode (FMC125 FW ≥ 03.28.05).
  /// </summary>
  public const ushort RfidIoId = 109;

  // -----------------------------------------------------------------------
  // Public API
  // -----------------------------------------------------------------------

  public sealed class RfidResult
  {
    /// <summary>
    /// Sequence counter of this Serial Packet within the current session (0-based).
    /// Sourced from the first byte of the IO 109 value envelope.
    /// </summary>
    public byte PacketIndex { get; init; }

    /// <summary>
    /// Declared length of the raw RS-232 payload, as written by the FMC125.
    /// Sourced from the second byte of the IO 109 value envelope.
    /// </summary>
    public byte DeclaredDataLength { get; init; }

    /// <summary>Raw RS-232 payload bytes (after stripping the 2-byte envelope header) as uppercase hex.</summary>
    public string RawHex { get; init; } = string.Empty;

    /// <summary>Printable ASCII representation of the payload, or null if not ASCII-printable.</summary>
    public string? AsciiText { get; init; }

    /// <summary>Best-effort extracted tag identifier (EPC/TID) as hex.</summary>
    public string ExtractedTagHex { get; init; } = string.Empty;

    /// <summary>Strategy that produced the extracted tag value.</summary>
    public string ExtractionMethod { get; init; } = string.Empty;

    public void PrintToConsole(string imei, DateTimeOffset timestamp)
    {
      Console.WriteLine();
      Console.WriteLine("╔══════════════════════════════════════════════════╗");
      Console.WriteLine("║     RS-232 DELIMITER / RFID  — IO 109 DETECTED   ║");
      Console.WriteLine("╠══════════════════════════════════════════════════╣");
      Console.WriteLine($"║  IMEI        : {imei}");
      Console.WriteLine($"║  Timestamp   : {timestamp:yyyy-MM-dd HH:mm:ss.fff} UTC");
      Console.WriteLine($"║  Pkt Index   : {PacketIndex}");
      Console.WriteLine($"║  Data Len    : {DeclaredDataLength} bytes");
      Console.WriteLine($"║  Raw HEX     : {RawHex}");
      Console.WriteLine($"║  ASCII       : {AsciiText ?? "(non-printable)"}");
      Console.WriteLine($"║  Tag HEX     : {ExtractedTagHex}");
      Console.WriteLine($"║  Method      : {ExtractionMethod}");
      Console.WriteLine("╚══════════════════════════════════════════════════╝");
      Console.WriteLine();
    }
  }

  /// <summary>
  /// Decodes the raw <see cref="IoElement.Value"/> bytes of IO 109 into
  /// a <see cref="RfidResult"/>.
  ///
  /// Per the FMC125 RS-232 Delimiter mode spec, the Value bytes have the envelope:
  ///   [0]  Index      — packet sequence counter (1 byte)
  ///   [1]  DataLength — byte count of the following payload (1 byte)
  ///   [2…] Payload    — actual RS-232 data (up to 255 bytes)
  ///
  /// The envelope header is stripped before running the decoding strategies.
  /// </summary>
  public static RfidResult Decode(byte[] ioValue)
  {
    ArgumentNullException.ThrowIfNull(ioValue);

    // ── Parse the IO 109 envelope header ────────────────────────────────
    if (ioValue.Length < 2)
    {
      // Malformed — too short to contain even the header.
      return new RfidResult
      {
        PacketIndex = 0,
        DeclaredDataLength = 0,
        RawHex = Convert.ToHexString(ioValue),
        AsciiText = null,
        ExtractedTagHex = Convert.ToHexString(ioValue),
        ExtractionMethod = "malformed (no envelope header)"
      };
    }

    byte packetIndex = ioValue[0];
    byte declaredLen = ioValue[1];

    // Guard: clamp to what is actually available after the 2-byte header.
    int availablePayloadBytes = ioValue.Length - 2;
    int payloadLen = Math.Min(declaredLen, availablePayloadBytes);

    byte[] payload = new byte[payloadLen];
    if (payloadLen > 0)
      Buffer.BlockCopy(ioValue, 2, payload, 0, payloadLen);

    // ── Decode the payload field ─────────────────────────────────────────
    string rawHex = Convert.ToHexString(payload);
    string? ascii = TryDecodeAsAscii(payload);

    string tagHex;
    string method;

    // Strategy 1 — pure printable ASCII that looks like a hex string
    // (reader already sent the EPC/TID as ASCII text)
    if (ascii is not null && LooksLikeHexString(ascii))
    {
      tagHex = ascii.Trim().ToUpperInvariant();
      method = "ASCII hex string";
      return new RfidResult
      {
        PacketIndex = packetIndex,
        DeclaredDataLength = declaredLen,
        RawHex = rawHex,
        AsciiText = ascii,
        ExtractedTagHex = tagHex,
        ExtractionMethod = method
      };
    }

    // Strategy 2 — known framed binary protocol patterns
    if (TryExtractFramedTag(payload, out tagHex!, out method!))
    {
      return new RfidResult
      {
        PacketIndex = packetIndex,
        DeclaredDataLength = declaredLen,
        RawHex = rawHex,
        AsciiText = ascii,
        ExtractedTagHex = tagHex,
        ExtractionMethod = method
      };
    }

    // Strategy 3 — heuristic: find a plausible EPC/TID run
    if (TryHeuristicExtract(payload, out tagHex!, out method!))
    {
      return new RfidResult
      {
        PacketIndex = packetIndex,
        DeclaredDataLength = declaredLen,
        RawHex = rawHex,
        AsciiText = ascii,
        ExtractedTagHex = tagHex,
        ExtractionMethod = method
      };
    }

    // Strategy 4 — fallback: return entire payload as-is
    return new RfidResult
    {
      PacketIndex = packetIndex,
      DeclaredDataLength = declaredLen,
      RawHex = rawHex,
      AsciiText = ascii,
      ExtractedTagHex = rawHex,
      ExtractionMethod = "fallback (full payload)"
    };
  }

  // -----------------------------------------------------------------------
  // Private helpers
  // -----------------------------------------------------------------------

  private static string? TryDecodeAsAscii(byte[] payload)
  {
    if (payload.Length == 0) return null;
    if (!BigEndianReader.IsPrintableAscii(payload)) return null;
    return Encoding.ASCII.GetString(payload);
  }

  private static bool LooksLikeHexString(string text)
  {
    string stripped = text.Trim().Replace(" ", "").Replace(":", "");
    if (stripped.Length < 4 || stripped.Length % 2 != 0) return false;
    foreach (char c in stripped)
    {
      if (!Uri.IsHexDigit(c)) return false;
    }
    return true;
  }

  /// <summary>
  /// Attempts to detect and parse common RS-232 RFID reader frame formats.
  ///
  /// Supported patterns:
  ///   A) CF 00 ... {epc_bytes} ...  — Feig / generic short-frame
  ///      Byte 0   = 0xCF (start of frame marker seen in sample data)
  ///      Byte 1-2 = 0x00 0x00 (flags / status)
  ///      Tag data is extracted from a known offset with a length hint.
  ///
  ///   B) AA BB {len} {tag...} {crc}  — generic LV frame
  ///      SOF = 0xAA, SOF2 = 0xBB, followed by 1-byte length.
  /// </summary>
  private static bool TryExtractFramedTag(
      byte[] payload,
      out string tagHex,
      out string method)
  {
    tagHex = string.Empty;
    method = string.Empty;

    // Pattern A: starts with 0xCF, minimum 8 bytes
    // Observed layout (from sample in requirements):
    //   CF 00 00 01 12 00 FD BC 01 00 0C DA 20 23 00 00 00 00 00 22 51 91 CA 24 92
    //   The last 6 bytes (indices -6..) are the EPC/TID.
    if (payload.Length >= 8 && payload[0] == 0xCF)
    {
      // Look for EPC/TID: typically the last 6–12 bytes of the frame
      // after stripping known header bytes.
      // Heuristic: skip first 4 header bytes, take up to last 12 bytes.
      int headerLen = 4;
      int remaining = payload.Length - headerLen;

      // Try to read a length field at byte [4] if present
      if (payload.Length > headerLen + 1)
      {
        // Try 6-byte, 8-byte, and 12-byte tag lengths from the end.
        foreach (int tagLen in new[] { 6, 8, 12 })
        {
          if (remaining >= tagLen)
          {
            int start = payload.Length - tagLen;
            tagHex = Convert.ToHexString(payload, start, tagLen);
            method = $"CF-frame heuristic tail ({tagLen} bytes)";
            return true;
          }
        }
      }
    }

    // Pattern B: SOF AA BB {1-byte length} {tag data} ...
    if (payload.Length >= 4 && payload[0] == 0xAA && payload[1] == 0xBB)
    {
      int tagLen = payload[2];
      if (tagLen > 0 && 3 + tagLen <= payload.Length)
      {
        tagHex = Convert.ToHexString(payload, 3, tagLen);
        method = "AA-BB LV frame";
        return true;
      }
    }

    return false;
  }

  /// <summary>
  /// Fallback heuristic: scans the payload for the longest run of bytes that
  /// don't look like protocol framing (non-zero, not all 0xFF padding, etc.)
  /// and whose length is 6–12 (even) — typical for UHF EPC96 tags.
  /// </summary>
  private static bool TryHeuristicExtract(
      byte[] payload,
      out string tagHex,
      out string method)
  {
    tagHex = string.Empty;
    method = string.Empty;

    if (payload.Length < 4) return false;

    // Try every possible even-length window from the minimum (6) to max (12).
    for (int tagLen = 12; tagLen >= 6; tagLen -= 2)
    {
      for (int start = 0; start + tagLen <= payload.Length; start++)
      {
        var window = new ReadOnlySpan<byte>(payload, start, tagLen);

        // Reject all-zeroes or all-0xFF runs.
        bool allZero = true, allFF = true;
        foreach (byte b in window)
        {
          if (b != 0x00) allZero = false;
          if (b != 0xFF) allFF = false;
        }
        if (allZero || allFF) continue;

        // Prefer tail of the frame (most readers put the EPC at the end).
        if (start == payload.Length - tagLen)
        {
          tagHex = Convert.ToHexString(payload, start, tagLen);
          method = $"heuristic tail window ({tagLen} bytes @ offset {start})";
          return true;
        }
      }
    }

    return false;
  }
}
